language: node_js
sudo: false
before_script:
  - npm install -g bower polylint web-component-tester
  - bower install
  - polylint
env:
  global:
    - CXX=g++-4.8
node_js: stable
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
      - ubuntu-toolchain-r-test
    packages:
      - google-chrome-stable
      - g++-4.8
  sauce_connect:
    username: "barvian"
    access_key:
      secure: "bZODeIbbysKuNcIEFkFh6hgf+PFKYHhAL6MhErjEOZr9pwZe2cjSzjxN3azPFwqj5uoyXdsDeuZ4IXsRzUzcYqaJBaoYvI61xcObxD2jQJ26SPw3+mZ6a8bhTqK+LDL9l8gySFQUTsRWHxX5bt+BG3mk2D2WzGiMqSHEVymSDNIptcWdP60/cIxP5+Mbamfg9bWIY+yS82mQaz0AuBLoodGaUoO2tKxcE/5W9o34Nm0e/YeSW+VDAaRYWcpqYalthdRU06OKNM6+q7JvTBL24SBbv8meH3e6PSPOcf82lVthmuMaju+H+lXN4ab4CrnDrWUu5m0ItnooYYHpLCfsk4DfBdG/n/02IcpvVtid7TBBzagMtOXMjVCUK/LgPJrlQtTlxMisy1wC7n44T6M7JHS9qkGqNzwmjzftJ+f+k9Zv4+AqNa3Kf/6csXU1EnDxwIhe/+3ftmEw+FaUMFjv68oxow3m1USRlcRvwFxmighBO3emBO5NMIVM5V160Cokg4iz7dytPftEtVgyH80IoHBFHHPIUoQd6qendRLkpeF0ugFSFiKcB2lIcQR+AHFugrDjhsOhZoLWXC2Ydu0fUIug5QsaVq7uuotIcV5x1qTlvGFa0PAtK0ItCZAP0YQUtZkSwHZ5Of2GvSVNLcf1WasA64DesjrCAdBMsZtGHlc="
script:
  - xvfb-run wct
  - "if [ \"${TRAVIS_PULL_REQUEST}\" = \"false\" ]; then wct -s 'default'; fi"
